# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8a61e07acb2e7ee1d46bb396bad1f0f9b1ad0b8b5daab2c6a318d1b0a12165edabb6359275d3c5f9f2f6dfc8288c973ec7ece8ba8c1b0d845753427a81ad4a

test:
  secret_key_base: fdcd8da0396f36ee594029a02f3940b121476e55708c471f183bcdeb015782df74ea5b3ef86fcdc055a1e53836af8423ea70123ae98396d4fe6e7c0dbe7e4557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
